### ISSUE TITLE
 tunnelbear up?  not working

### ISSUE THREAD

**Issue by tawanda** [JenniferMack/TunnelBear-Helper#1]
The up? argument not working in ZSH on Manjaro 

```
➜  ~  tunnelbear up?                            
zsh: no matches found: up?
```

**Comment by JenniferMack** [comment]
Would you test something for me? I don’t have zsh installed.

On line 46, delete the `?` and see if it works with just `tunnelbear up`. If it does, I’ll update the code.

**Comment by tawanda** [comment]
No problem, i'll test it out tomorrow on my machine at work

**Comment by tawanda** [comment]
I've changed the keyword on line 45 to 'status' so it matches with other Unix type queries and its working great

```
➜  bin  tunnelbear status
TunnelBear is roaring in UnitedKingdom (pid: 2947).
➜  bin  
```

Thanks for the great script
